require("dotenv").config();
const mongoose = require("mongoose");
const Ingredient = require("../models/ingredient.model.js");
const connectDB = require("../config/connectDB.js");

const ingredients = [
  { name: "Baguette", category: "bakery", caloriesPer100g: 248 },
  { name: "Bialy", category: "bakery", caloriesPer100g: 0 },
  { name: "Breadsticks", category: "bakery", caloriesPer100g: 0 },
  { name: "Brioche", category: "bakery", caloriesPer100g: 347 },
  { name: "Challah", category: "bakery", caloriesPer100g: 287 },
  { name: "Ciabatta", category: "bakery", caloriesPer100g: 250 },
  { name: "Corn Tortilla", category: "bakery", caloriesPer100g: 0 },
  { name: "Croissant", category: "bakery", caloriesPer100g: 406 },
  { name: "English Muffin", category: "bakery", caloriesPer100g: 0 },
  { name: "Focaccia", category: "bakery", caloriesPer100g: 249 },
  { name: "Hard Taco Shell", category: "bakery", caloriesPer100g: 0 },
  { name: "Hoagie Roll", category: "bakery", caloriesPer100g: 0 },
  { name: "Injera", category: "bakery", caloriesPer100g: 0 },
  { name: "Kaiser Roll", category: "bakery", caloriesPer100g: 0 },
  { name: "Kataifi", category: "bakery", caloriesPer100g: 0 },
  { name: "Lavash", category: "bakery", caloriesPer100g: 0 },
  { name: "Matzo", category: "bakery", caloriesPer100g: 0 },
  { name: "Naan", category: "bakery", caloriesPer100g: 290 },
  { name: "Pandoro", category: "bakery", caloriesPer100g: 0 },
  { name: "Panettone", category: "bakery", caloriesPer100g: 0 },
  { name: "Phyllo Dough", category: "bakery", caloriesPer100g: 0 },
  { name: "Pita Bread", category: "bakery", caloriesPer100g: 275 },
  { name: "Pizza Dough", category: "bakery", caloriesPer100g: 270 },
  { name: "Puff Pastry", category: "bakery", caloriesPer100g: 558 },
  { name: "Pumpernickel", category: "bakery", caloriesPer100g: 250 },
  { name: "Pupusa", category: "bakery", caloriesPer100g: 0 },
  { name: "Rye Bread", category: "bakery", caloriesPer100g: 259 },
  { name: "Soft Pretzel", category: "bakery", caloriesPer100g: 0 },
  { name: "Sourdough", category: "bakery", caloriesPer100g: 289 },
  { name: "Stollen", category: "bakery", caloriesPer100g: 0 },
  { name: "Tortilla", category: "bakery", caloriesPer100g: 218 },
  { name: "Asiago", category: "dairy", caloriesPer100g: 0 },
  { name: "Blue Cheese", category: "dairy", caloriesPer100g: 353 },
  { name: "Brie", category: "dairy", caloriesPer100g: 334 },
  { name: "Burrata", category: "dairy", caloriesPer100g: 250 },
  { name: "Butter", category: "dairy", caloriesPer100g: 717 },
  { name: "Caciocavallo", category: "dairy", caloriesPer100g: 0 },
  { name: "Caerphilly", category: "dairy", caloriesPer100g: 0 },
  { name: "Camembert", category: "dairy", caloriesPer100g: 300 },
  { name: "Cheddar Cheese", category: "dairy", caloriesPer100g: 402 },
  { name: "Clotted Cream", category: "dairy", caloriesPer100g: 0 },
  { name: "Comte", category: "dairy", caloriesPer100g: 0 },
  { name: "Cottage Cheese", category: "dairy", caloriesPer100g: 98 },
  { name: "Cream Cheese", category: "dairy", caloriesPer100g: 342 },
  { name: "Double Gloucester", category: "dairy", caloriesPer100g: 0 },
  { name: "Eggs", category: "dairy", caloriesPer100g: 155 },
  { name: "Emmental", category: "dairy", caloriesPer100g: 0 },
  { name: "Feta", category: "dairy", caloriesPer100g: 264 },
  { name: "Fontina", category: "dairy", caloriesPer100g: 0 },
  { name: "Fromage Blanc", category: "dairy", caloriesPer100g: 0 },
  { name: "Ghee", category: "dairy", caloriesPer100g: 900 },
  { name: "Goat Cheese", category: "dairy", caloriesPer100g: 364 },
  { name: "Gorgonzola", category: "dairy", caloriesPer100g: 350 },
  { name: "Gouda", category: "dairy", caloriesPer100g: 356 },
  { name: "Grana Padano", category: "dairy", caloriesPer100g: 0 },
  { name: "Greek Yogurt", category: "dairy", caloriesPer100g: 59 },
  { name: "Gruyere Cheese", category: "dairy", caloriesPer100g: 413 },
  { name: "Havarti", category: "dairy", caloriesPer100g: 371 },
  { name: "Kasseri", category: "dairy", caloriesPer100g: 0 },
  { name: "Kefalotyri", category: "dairy", caloriesPer100g: 0 },
  { name: "Kefir", category: "dairy", caloriesPer100g: 41 },
  { name: "Labneh", category: "dairy", caloriesPer100g: 0 },
  { name: "Limburger", category: "dairy", caloriesPer100g: 0 },
  { name: "Manchego Cheese", category: "dairy", caloriesPer100g: 410 },
  { name: "Mascarpone", category: "dairy", caloriesPer100g: 429 },
  { name: "Mascarpone Cheese", category: "dairy", caloriesPer100g: 429 },
  { name: "Milk", category: "dairy", caloriesPer100g: 42 },
  { name: "Mizithra", category: "dairy", caloriesPer100g: 0 },
  { name: "Morbier", category: "dairy", caloriesPer100g: 0 },
  { name: "Mozzarella Cheese", category: "dairy", caloriesPer100g: 280 },
  { name: "Munster Cheese", category: "dairy", caloriesPer100g: 0 },
  { name: "Oaxaca Cheese", category: "dairy", caloriesPer100g: 0 },
  { name: "Ossau-Iraty", category: "dairy", caloriesPer100g: 0 },
  { name: "Paneer", category: "dairy", caloriesPer100g: 0 },
  { name: "Parmesan Cheese", category: "dairy", caloriesPer100g: 431 },
  { name: "Pecorino Romano", category: "dairy", caloriesPer100g: 0 },
  { name: "Pecorino Toscano", category: "dairy", caloriesPer100g: 0 },
  { name: "Pont-l'Évêque", category: "dairy", caloriesPer100g: 0 },
  { name: "Provolone", category: "dairy", caloriesPer100g: 351 },
  { name: "Quark", category: "dairy", caloriesPer100g: 0 },
  { name: "Queso Fresco", category: "dairy", caloriesPer100g: 0 },
  { name: "Raclette", category: "dairy", caloriesPer100g: 0 },
  { name: "Red Leicester", category: "dairy", caloriesPer100g: 0 },
  { name: "Ricotta", category: "dairy", caloriesPer100g: 174 },
  { name: "Roquefort", category: "dairy", caloriesPer100g: 369 },
  { name: "Saint-Maure de Touraine", category: "dairy", caloriesPer100g: 0 },
  { name: "Sour Cream", category: "dairy", caloriesPer100g: 193 },
  { name: "Stilton", category: "dairy", caloriesPer100g: 0 },
  { name: "Swiss Cheese", category: "dairy", caloriesPer100g: 393 },
  { name: "Taleggio", category: "dairy", caloriesPer100g: 0 },
  { name: "Wensleydale", category: "dairy", caloriesPer100g: 0 },
  { name: "Époisses", category: "dairy", caloriesPer100g: 0 },
  { name: "Amberjack", category: "fish", caloriesPer100g: 0 },
  { name: "Anchovies", category: "fish", caloriesPer100g: 131 },
  { name: "Arctic Char", category: "fish", caloriesPer100g: 154 },
  { name: "Barramundi", category: "fish", caloriesPer100g: 108 },
  { name: "Branzino", category: "fish", caloriesPer100g: 0 },
  { name: "Capelin", category: "fish", caloriesPer100g: 0 },
  { name: "Catfish", category: "fish", caloriesPer100g: 95 },
  { name: "Cod", category: "fish", caloriesPer100g: 82 },
  { name: "Dover Sole", category: "fish", caloriesPer100g: 0 },
  { name: "Eel", category: "fish", caloriesPer100g: 184 },
  { name: "Flounder", category: "fish", caloriesPer100g: 91 },
  { name: "Grey Mullet", category: "fish", caloriesPer100g: 0 },
  { name: "Grouper", category: "fish", caloriesPer100g: 92 },
  { name: "Haddock", category: "fish", caloriesPer100g: 0 },
  { name: "Hake", category: "fish", caloriesPer100g: 0 },
  { name: "Halibut", category: "fish", caloriesPer100g: 111 },
  { name: "Herring", category: "fish", caloriesPer100g: 158 },
  { name: "Lemon Sole", category: "fish", caloriesPer100g: 0 },
  { name: "Mackerel", category: "fish", caloriesPer100g: 205 },
  { name: "Mahi Mahi", category: "fish", caloriesPer100g: 85 },
  { name: "Monkfish", category: "fish", caloriesPer100g: 76 },
  { name: "Perch", category: "fish", caloriesPer100g: 91 },
  { name: "Pike", category: "fish", caloriesPer100g: 88 },
  { name: "Plaice", category: "fish", caloriesPer100g: 0 },
  { name: "Pollock", category: "fish", caloriesPer100g: 0 },
  { name: "Red Mullet", category: "fish", caloriesPer100g: 0 },
  { name: "Salmon", category: "fish", caloriesPer100g: 208 },
  { name: "Sardines", category: "fish", caloriesPer100g: 208 },
  { name: "Smelt", category: "fish", caloriesPer100g: 0 },
  { name: "Snapper", category: "fish", caloriesPer100g: 100 },
  { name: "Sole", category: "fish", caloriesPer100g: 91 },
  { name: "Sturgeon", category: "fish", caloriesPer100g: 0 },
  { name: "Swordfish", category: "fish", caloriesPer100g: 172 },
  { name: "Tilapia", category: "fish", caloriesPer100g: 96 },
  { name: "Trout", category: "fish", caloriesPer100g: 141 },
  { name: "Tuna", category: "fish", caloriesPer100g: 132 },
  { name: "Turbot", category: "fish", caloriesPer100g: 0 },
  { name: "Whitebait", category: "fish", caloriesPer100g: 0 },
  { name: "Whiting", category: "fish", caloriesPer100g: 0 },
  { name: "Yellowtail", category: "fish", caloriesPer100g: 0 },
  { name: "Apple", category: "fruit", caloriesPer100g: 52 },
  { name: "Apricot", category: "fruit", caloriesPer100g: 48 },
  { name: "Avocado", category: "fruit", caloriesPer100g: 160 },
  { name: "Banana", category: "fruit", caloriesPer100g: 89 },
  { name: "Black Sapote", category: "fruit", caloriesPer100g: 0 },
  { name: "Blackberry", category: "fruit", caloriesPer100g: 43 },
  { name: "Blackcurrant", category: "fruit", caloriesPer100g: 0 },
  { name: "Blood Orange", category: "fruit", caloriesPer100g: 50 },
  { name: "Blueberry", category: "fruit", caloriesPer100g: 57 },
  { name: "Boysenberry", category: "fruit", caloriesPer100g: 50 },
  { name: "Breadfruit", category: "fruit", caloriesPer100g: 0 },
  { name: "Cactus Pear", category: "fruit", caloriesPer100g: 0 },
  { name: "Calamansi", category: "fruit", caloriesPer100g: 0 },
  { name: "Canary Melon", category: "fruit", caloriesPer100g: 0 },
  { name: "Canistel", category: "fruit", caloriesPer100g: 0 },
  { name: "Cantaloupe", category: "fruit", caloriesPer100g: 34 },
  { name: "Cherimoya", category: "fruit", caloriesPer100g: 0 },
  { name: "Cherry", category: "fruit", caloriesPer100g: 50 },
  { name: "Cloudberry", category: "fruit", caloriesPer100g: 0 },
  { name: "Coconut", category: "fruit", caloriesPer100g: 354 },
  { name: "Cranberry", category: "fruit", caloriesPer100g: 46 },
  { name: "Crenshaw Melon", category: "fruit", caloriesPer100g: 0 },
  { name: "Damson Plum", category: "fruit", caloriesPer100g: 0 },
  { name: "Date", category: "fruit", caloriesPer100g: 282 },
  { name: "Dragon Fruit", category: "fruit", caloriesPer100g: 60 },
  { name: "Durian", category: "fruit", caloriesPer100g: 147 },
  { name: "Elderberry", category: "fruit", caloriesPer100g: 73 },
  { name: "Feijoa", category: "fruit", caloriesPer100g: 0 },
  { name: "Fig", category: "fruit", caloriesPer100g: 74 },
  { name: "Finger Lime", category: "fruit", caloriesPer100g: 0 },
  { name: "Galia Melon", category: "fruit", caloriesPer100g: 0 },
  { name: "Gooseberry", category: "fruit", caloriesPer100g: 44 },
  { name: "Grape", category: "fruit", caloriesPer100g: 69 },
  { name: "Grapefruit", category: "fruit", caloriesPer100g: 42 },
  { name: "Guava", category: "fruit", caloriesPer100g: 68 },
  { name: "Honeydew", category: "fruit", caloriesPer100g: 36 },
  { name: "Jackfruit", category: "fruit", caloriesPer100g: 95 },
  { name: "Jujube", category: "fruit", caloriesPer100g: 0 },
  { name: "Key Lime", category: "fruit", caloriesPer100g: 0 },
  { name: "Kiwi", category: "fruit", caloriesPer100g: 61 },
  { name: "Korean Melon", category: "fruit", caloriesPer100g: 0 },
  { name: "Kumquat", category: "fruit", caloriesPer100g: 71 },
  { name: "Lemon", category: "fruit", caloriesPer100g: 29 },
  { name: "Lime", category: "fruit", caloriesPer100g: 30 },
  { name: "Loganberry", category: "fruit", caloriesPer100g: 0 },
  { name: "Longan", category: "fruit", caloriesPer100g: 0 },
  { name: "Loquat", category: "fruit", caloriesPer100g: 0 },
  { name: "Lychee", category: "fruit", caloriesPer100g: 66 },
  { name: "Mamey Sapote", category: "fruit", caloriesPer100g: 0 },
  { name: "Mango", category: "fruit", caloriesPer100g: 60 },
  { name: "Mangosteen", category: "fruit", caloriesPer100g: 73 },
  { name: "Medlar", category: "fruit", caloriesPer100g: 0 },
  { name: "Meyer Lemon", category: "fruit", caloriesPer100g: 0 },
  { name: "Mirabelle Plum", category: "fruit", caloriesPer100g: 0 },
  { name: "Mulberry", category: "fruit", caloriesPer100g: 0 },
  { name: "Nectarine", category: "fruit", caloriesPer100g: 44 },
  { name: "Orange", category: "fruit", caloriesPer100g: 47 },
  { name: "Papaya", category: "fruit", caloriesPer100g: 43 },
  { name: "Passion Fruit", category: "fruit", caloriesPer100g: 97 },
  { name: "Pawpaw", category: "fruit", caloriesPer100g: 0 },
  { name: "Peach", category: "fruit", caloriesPer100g: 39 },
  { name: "Pear", category: "fruit", caloriesPer100g: 57 },
  { name: "Persimmon", category: "fruit", caloriesPer100g: 70 },
  { name: "Physalis", category: "fruit", caloriesPer100g: 0 },
  { name: "Piel de Sapo", category: "fruit", caloriesPer100g: 0 },
  { name: "Pineapple", category: "fruit", caloriesPer100g: 50 },
  { name: "Plantain", category: "fruit", caloriesPer100g: 122 },
  { name: "Plum", category: "fruit", caloriesPer100g: 46 },
  { name: "Pomelo", category: "fruit", caloriesPer100g: 0 },
  { name: "Pomegranate", category: "fruit", caloriesPer100g: 83 },
  { name: "Quince", category: "fruit", caloriesPer100g: 57 },
  { name: "Rambutan", category: "fruit", caloriesPer100g: 82 },
  { name: "Raspberry", category: "fruit", caloriesPer100g: 52 },
  { name: "Redcurrant", category: "fruit", caloriesPer100g: 0 },
  { name: "Rose Hip", category: "fruit", caloriesPer100g: 0 },
  { name: "Sapodilla", category: "fruit", caloriesPer100g: 0 },
  { name: "Sea Buckthorn", category: "fruit", caloriesPer100g: 0 },
  { name: "Soursop", category: "fruit", caloriesPer100g: 0 },
  { name: "Star Fruit", category: "fruit", caloriesPer100g: 31 },
  { name: "Strawberry", category: "fruit", caloriesPer100g: 32 },
  { name: "Tangerine", category: "fruit", caloriesPer100g: 53 },
  { name: "Watermelon", category: "fruit", caloriesPer100g: 30 },
  { name: "Yuzu", category: "fruit", caloriesPer100g: 0 },
  { name: "Arborio Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Barley", category: "grain", caloriesPer100g: 354 },
  { name: "Basmati Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Black Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Brown Rice", category: "grain", caloriesPer100g: 111 },
  { name: "Buckwheat Groats", category: "grain", caloriesPer100g: 0 },
  { name: "Bulgur", category: "grain", caloriesPer100g: 83 },
  { name: "Carnaroli Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Cornmeal", category: "grain", caloriesPer100g: 370 },
  { name: "Couscous", category: "grain", caloriesPer100g: 112 },
  { name: "Farro", category: "grain", caloriesPer100g: 362 },
  { name: "Jasmine Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Job's Tears", category: "grain", caloriesPer100g: 0 },
  { name: "Oats", category: "grain", caloriesPer100g: 389 },
  { name: "Quinoa", category: "grain", caloriesPer100g: 120 },
  { name: "Red Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Rolled Oats", category: "grain", caloriesPer100g: 0 },
  { name: "Semolina", category: "grain", caloriesPer100g: 0 },
  { name: "Steel Cut Oats", category: "grain", caloriesPer100g: 0 },
  { name: "Sticky Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Sushi Rice", category: "grain", caloriesPer100g: 0 },
  { name: "Triticale", category: "grain", caloriesPer100g: 0 },
  { name: "Wheat Bran", category: "grain", caloriesPer100g: 0 },
  { name: "Wheat Berries", category: "grain", caloriesPer100g: 0 },
  { name: "Wheat Flour", category: "grain", caloriesPer100g: 364 },
  { name: "Wheat Germ", category: "grain", caloriesPer100g: 0 },
  { name: "White Rice", category: "grain", caloriesPer100g: 130 },
  { name: "Wild Rice", category: "grain", caloriesPer100g: 101 },
  { name: "Avocado Leaves", category: "herb", caloriesPer100g: 0 },
  { name: "Basil", category: "herb", caloriesPer100g: 23 },
  { name: "Bay Leaf", category: "herb", caloriesPer100g: 313 },
  { name: "Borage", category: "herb", caloriesPer100g: 0 },
  { name: "Chervil", category: "herb", caloriesPer100g: 237 },
  { name: "Chives", category: "herb", caloriesPer100g: 30 },
  { name: "Cilantro", category: "herb", caloriesPer100g: 23 },
  { name: "Culantro", category: "herb", caloriesPer100g: 0 },
  { name: "Dill", category: "herb", caloriesPer100g: 43 },
  { name: "Epazote", category: "herb", caloriesPer100g: 0 },
  { name: "Holy Basil", category: "herb", caloriesPer100g: 0 },
  { name: "Hoja Santa", category: "herb", caloriesPer100g: 0 },
  { name: "Lavender", category: "herb", caloriesPer100g: 0 },
  { name: "Lemon Balm", category: "herb", caloriesPer100g: 0 },
  { name: "Lemon Basil", category: "herb", caloriesPer100g: 0 },
  { name: "Lemon Verbena", category: "herb", caloriesPer100g: 0 },
  { name: "Lemongrass", category: "herb", caloriesPer100g: 99 },
  { name: "Lovage", category: "herb", caloriesPer100g: 0 },
  { name: "Marjoram", category: "herb", caloriesPer100g: 271 },
  { name: "Mint", category: "herb", caloriesPer100g: 70 },
  { name: "Mitsuba", category: "herb", caloriesPer100g: 0 },
  { name: "Oregano", category: "herb", caloriesPer100g: 265 },
  { name: "Pandan Leaves", category: "herb", caloriesPer100g: 0 },
  { name: "Parsley", category: "herb", caloriesPer100g: 36 },
  { name: "Pineapple Sage", category: "herb", caloriesPer100g: 0 },
  { name: "Rau Ram", category: "herb", caloriesPer100g: 0 },
  { name: "Rosemary", category: "herb", caloriesPer100g: 131 },
  { name: "Sage", category: "herb", caloriesPer100g: 315 },
  { name: "Savory", category: "herb", caloriesPer100g: 272 },
  { name: "Shiso", category: "herb", caloriesPer100g: 0 },
  { name: "Sorrel", category: "herb", caloriesPer100g: 22 },
  { name: "Summer Savory", category: "herb", caloriesPer100g: 0 },
  { name: "Sweet Cicely", category: "herb", caloriesPer100g: 0 },
  { name: "Tarragon", category: "herb", caloriesPer100g: 295 },
  { name: "Thai Basil", category: "herb", caloriesPer100g: 0 },
  { name: "Thyme", category: "herb", caloriesPer100g: 101 },
  { name: "Winter Savory", category: "herb", caloriesPer100g: 0 },
  { name: "Anasazi Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Adzuki Beans", category: "legume", caloriesPer100g: 128 },
  { name: "Black Beans", category: "legume", caloriesPer100g: 132 },
  { name: "Black Eyed Peas", category: "legume", caloriesPer100g: 0 },
  { name: "Black Turtle Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Borlotti Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Butter Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Cannellini Beans", category: "legume", caloriesPer100g: 139 },
  { name: "Chana Dal", category: "legume", caloriesPer100g: 0 },
  { name: "Chickpeas", category: "legume", caloriesPer100g: 164 },
  { name: "Edamame", category: "legume", caloriesPer100g: 122 },
  { name: "Fava Beans", category: "legume", caloriesPer100g: 110 },
  { name: "Flageolet Beans", category: "legume", caloriesPer100g: 100 },
  { name: "Great Northern Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Horse Gram", category: "legume", caloriesPer100g: 0 },
  { name: "Kidney Beans", category: "legume", caloriesPer100g: 127 },
  { name: "Lentils", category: "legume", caloriesPer100g: 116 },
  { name: "Lima Beans", category: "legume", caloriesPer100g: 115 },
  { name: "Lupini Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Masoor Dal", category: "legume", caloriesPer100g: 0 },
  { name: "Moong Dal", category: "legume", caloriesPer100g: 0 },
  { name: "Moth Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Mung Beans", category: "legume", caloriesPer100g: 105 },
  { name: "Navy Beans", category: "legume", caloriesPer100g: 139 },
  { name: "Pigeon Peas", category: "legume", caloriesPer100g: 0 },
  { name: "Pinto Beans", category: "legume", caloriesPer100g: 143 },
  { name: "Runner Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Scarlet Runner Beans", category: "legume", caloriesPer100g: 0 },
  { name: "Soybeans", category: "legume", caloriesPer100g: 173 },
  { name: "Split Peas", category: "legume", caloriesPer100g: 118 },
  { name: "Toor Dal", category: "legume", caloriesPer100g: 0 },
  { name: "Urad Dal", category: "legume", caloriesPer100g: 0 },
  { name: "Alligator Tail", category: "meat", caloriesPer100g: 0 },
  { name: "Bacon", category: "meat", caloriesPer100g: 541 },
  { name: "Beef Chuck Roast", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Flank Steak", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Heart", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Kidney", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Liver", category: "meat", caloriesPer100g: 135 },
  { name: "Beef Picanha", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Short Ribs", category: "meat", caloriesPer100g: 471 },
  { name: "Beef Tongue", category: "meat", caloriesPer100g: 0 },
  { name: "Beef Tripe", category: "meat", caloriesPer100g: 0 },
  { name: "Bison", category: "meat", caloriesPer100g: 143 },
  { name: "Bone Marrow", category: "meat", caloriesPer100g: 0 },
  { name: "Brisket", category: "meat", caloriesPer100g: 0 },
  { name: "Chicken Breast", category: "meat", caloriesPer100g: 165 },
  { name: "Chicken Drumstick", category: "meat", caloriesPer100g: 172 },
  { name: "Chicken Feet", category: "meat", caloriesPer100g: 0 },
  { name: "Chicken Gizzard", category: "meat", caloriesPer100g: 0 },
  { name: "Chicken Thigh", category: "meat", caloriesPer100g: 209 },
  { name: "Chicken Wings", category: "meat", caloriesPer100g: 203 },
  { name: "Chorizo", category: "meat", caloriesPer100g: 455 },
  { name: "Duck Breast", category: "meat", caloriesPer100g: 337 },
  { name: "Duck Fat", category: "meat", caloriesPer100g: 0 },
  { name: "Duck Leg", category: "meat", caloriesPer100g: 0 },
  { name: "Elk Meat", category: "meat", caloriesPer100g: 0 },
  { name: "Foie Gras", category: "meat", caloriesPer100g: 0 },
  { name: "Goose", category: "meat", caloriesPer100g: 371 },
  { name: "Ground Beef", category: "meat", caloriesPer100g: 250 },
  { name: "Guinea Fowl", category: "meat", caloriesPer100g: 0 },
  { name: "Ham", category: "meat", caloriesPer100g: 145 },
  { name: "Hanger Steak", category: "meat", caloriesPer100g: 0 },
  { name: "Kangaroo Meat", category: "meat", caloriesPer100g: 0 },
  { name: "Lamb Chop", category: "meat", caloriesPer100g: 294 },
  { name: "Lamb Neck", category: "meat", caloriesPer100g: 0 },
  { name: "Lamb Rack", category: "meat", caloriesPer100g: 0 },
  { name: "Lamb Shank", category: "meat", caloriesPer100g: 0 },
  { name: "Ostrich Steak", category: "meat", caloriesPer100g: 0 },
  { name: "Oxtail", category: "meat", caloriesPer100g: 262 },
  { name: "Pancetta", category: "meat", caloriesPer100g: 450 },
  { name: "Pepperoni", category: "meat", caloriesPer100g: 494 },
  { name: "Pheasant", category: "meat", caloriesPer100g: 239 },
  { name: "Pork Belly", category: "meat", caloriesPer100g: 518 },
  { name: "Pork Chop", category: "meat", caloriesPer100g: 231 },
  { name: "Pork Hock", category: "meat", caloriesPer100g: 0 },
  { name: "Pork Jowl", category: "meat", caloriesPer100g: 0 },
  { name: "Pork Loin", category: "meat", caloriesPer100g: 242 },
  { name: "Pork Shoulder", category: "meat", caloriesPer100g: 0 },
  { name: "Pork Trotters", category: "meat", caloriesPer100g: 0 },
  { name: "Prosciutto", category: "meat", caloriesPer100g: 242 },
  { name: "Quail", category: "meat", caloriesPer100g: 192 },
  { name: "Rabbit", category: "meat", caloriesPer100g: 173 },
  { name: "Salami", category: "meat", caloriesPer100g: 336 },
  { name: "Sausage", category: "meat", caloriesPer100g: 301 },
  { name: "Skirt Steak", category: "meat", caloriesPer100g: 0 },
  { name: "Squab", category: "meat", caloriesPer100g: 0 },
  { name: "Steak", category: "meat", caloriesPer100g: 271 },
  { name: "Sweetbreads", category: "meat", caloriesPer100g: 0 },
  { name: "Tri-Tip", category: "meat", caloriesPer100g: 0 },
  { name: "Turkey Breast", category: "meat", caloriesPer100g: 135 },
  { name: "Veal", category: "meat", caloriesPer100g: 172 },
  { name: "Veal Scallopini", category: "meat", caloriesPer100g: 0 },
  { name: "Veal Shank", category: "meat", caloriesPer100g: 0 },
  { name: "Venison", category: "meat", caloriesPer100g: 158 },
  { name: "Venison Sausage", category: "meat", caloriesPer100g: 0 },
  { name: "Wild Boar", category: "meat", caloriesPer100g: 0 },
  { name: "Almond Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Avocado Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Black Truffle Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Canola Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Coconut Oil", category: "oil", caloriesPer100g: 862 },
  { name: "Cottonseed Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Flaxseed Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Grapeseed Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Hazelnut Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Macadamia Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Mustard Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Olive Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Peanut Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Pistachio Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Pumpkin Seed Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Rice Bran Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Sesame Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Sunflower Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Truffle Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Vegetable Oil", category: "oil", caloriesPer100g: 884 },
  { name: "Walnut Oil", category: "oil", caloriesPer100g: 884 },
  { name: "White Truffle Oil", category: "oil", caloriesPer100g: 0 },
  { name: "Agar Agar", category: "other", caloriesPer100g: 26 },
  { name: "Ajvar", category: "other", caloriesPer100g: 0 },
  { name: "Almonds", category: "other", caloriesPer100g: 0 },
  { name: "Apple Cider Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Apricot Kernels", category: "other", caloriesPer100g: 0 },
  { name: "Baba Ganoush", category: "other", caloriesPer100g: 0 },
  { name: "Baking Powder", category: "other", caloriesPer100g: 53 },
  { name: "Baking Soda", category: "other", caloriesPer100g: 0 },
  { name: "Balsamic Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Black Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Black Sesame Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Brazil Nuts", category: "other", caloriesPer100g: 0 },
  { name: "Cane Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Cashews", category: "other", caloriesPer100g: 0 },
  { name: "Cellophane Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Champagne Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Chestnuts", category: "other", caloriesPer100g: 0 },
  { name: "Chia Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Chocolate Chips", category: "other", caloriesPer100g: 480 },
  { name: "Cocoa Nibs", category: "other", caloriesPer100g: 0 },
  { name: "Cocoa Powder", category: "other", caloriesPer100g: 228 },
  { name: "Coconut Cream", category: "other", caloriesPer100g: 0 },
  { name: "Coconut Milk", category: "other", caloriesPer100g: 0 },
  { name: "Coconut Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Egg Roll Wrappers", category: "other", caloriesPer100g: 0 },
  { name: "Extra Firm Tofu", category: "other", caloriesPer100g: 0 },
  { name: "Fermented Bean Curd", category: "other", caloriesPer100g: 0 },
  { name: "Fettuccine Pasta", category: "other", caloriesPer100g: 0 },
  { name: "Firm Tofu", category: "other", caloriesPer100g: 0 },
  { name: "Fish Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Flax Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Fusilli Pasta", category: "other", caloriesPer100g: 0 },
  { name: "Gnocchi", category: "other", caloriesPer100g: 0 },
  { name: "Gochujang", category: "other", caloriesPer100g: 200 },
  { name: "Harissa", category: "other", caloriesPer100g: 120 },
  { name: "Hazelnuts", category: "other", caloriesPer100g: 0 },
  { name: "Hemp Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Ho Fun Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Hoisin Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Hummus", category: "other", caloriesPer100g: 0 },
  { name: "Kimchi", category: "other", caloriesPer100g: 0 },
  { name: "Linguine Pasta", category: "other", caloriesPer100g: 0 },
  { name: "Liquid Smoke", category: "other", caloriesPer100g: 0 },
  { name: "Lo Mein Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Lotus Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Macadamia Nuts", category: "other", caloriesPer100g: 0 },
  { name: "Malt Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Miso", category: "other", caloriesPer100g: 199 },
  { name: "Muhammara", category: "other", caloriesPer100g: 0 },
  { name: "Nutritional Yeast", category: "other", caloriesPer100g: 325 },
  { name: "Orzo Pasta", category: "other", caloriesPer100g: 0 },
  { name: "Oyster Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Pesto", category: "other", caloriesPer100g: 400 },
  { name: "Pili Nuts", category: "other", caloriesPer100g: 0 },
  { name: "Pine Nuts", category: "other", caloriesPer100g: 0 },
  { name: "Pistachios", category: "other", caloriesPer100g: 0 },
  { name: "Plum Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Poppy Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Pumpkin Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Ramen Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Ravioli", category: "other", caloriesPer100g: 0 },
  { name: "Red Wine Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Rice Paper", category: "other", caloriesPer100g: 0 },
  { name: "Rice Vermicelli", category: "other", caloriesPer100g: 0 },
  { name: "Rice Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Rigatoni Pasta", category: "other", caloriesPer100g: 0 },
  { name: "Salt", category: "other", caloriesPer100g: 0 },
  { name: "Sambal Oelek", category: "other", caloriesPer100g: 0 },
  { name: "Sauerkraut", category: "other", caloriesPer100g: 0 },
  { name: "Seitan", category: "other", caloriesPer100g: 0 },
  { name: "Sherry Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Silken Tofu", category: "other", caloriesPer100g: 0 },
  { name: "Soba Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Soft Tofu", category: "other", caloriesPer100g: 0 },
  { name: "Soy Sauce", category: "other", caloriesPer100g: 53 },
  { name: "Spring Roll Wrappers", category: "other", caloriesPer100g: 0 },
  { name: "Sriracha Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Sunflower Seeds", category: "other", caloriesPer100g: 0 },
  { name: "Sushi Rice", category: "other", caloriesPer100g: 0 },
  { name: "Sweet Chili Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Tahini", category: "other", caloriesPer100g: 595 },
  { name: "Tamarind", category: "other", caloriesPer100g: 239 },
  { name: "Tapenade", category: "other", caloriesPer100g: 0 },
  { name: "Tarragon Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Tempeh", category: "other", caloriesPer100g: 0 },
  { name: "Tigers Nuts", category: "other", caloriesPer100g: 0 },
  { name: "Tofu Skin", category: "other", caloriesPer100g: 0 },
  { name: "Tortellini", category: "other", caloriesPer100g: 0 },
  { name: "Udon Noodles", category: "other", caloriesPer100g: 0 },
  { name: "Vanilla Bean", category: "other", caloriesPer100g: 288 },
  { name: "Vanilla Extract", category: "other", caloriesPer100g: 288 },
  { name: "Walnuts", category: "other", caloriesPer100g: 0 },
  { name: "Water", category: "other", caloriesPer100g: 0 },
  { name: "Watermelon Seeds", category: "other", caloriesPer100g: 0 },
  { name: "White Sesame Seeds", category: "other", caloriesPer100g: 0 },
  { name: "White Wine Vinegar", category: "other", caloriesPer100g: 0 },
  { name: "Wonton Wrappers", category: "other", caloriesPer100g: 0 },
  { name: "Worcestershire Sauce", category: "other", caloriesPer100g: 0 },
  { name: "Yeast", category: "other", caloriesPer100g: 325 },
  { name: "Abalone", category: "seafood", caloriesPer100g: 105 },
  { name: "Blue Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Bottarga", category: "seafood", caloriesPer100g: 0 },
  { name: "Cherrystone Clams", category: "seafood", caloriesPer100g: 0 },
  { name: "Clams", category: "seafood", caloriesPer100g: 74 },
  { name: "Cockles", category: "seafood", caloriesPer100g: 79 },
  { name: "Crab", category: "seafood", caloriesPer100g: 84 },
  { name: "Crawfish", category: "seafood", caloriesPer100g: 0 },
  { name: "Cuttlefish", category: "seafood", caloriesPer100g: 79 },
  { name: "Dungeness Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Geoduck", category: "seafood", caloriesPer100g: 0 },
  { name: "King Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Langoustine", category: "seafood", caloriesPer100g: 0 },
  { name: "Littleneck Clams", category: "seafood", caloriesPer100g: 0 },
  { name: "Lobster", category: "seafood", caloriesPer100g: 89 },
  { name: "Mantis Shrimp", category: "seafood", caloriesPer100g: 0 },
  { name: "Mussels", category: "seafood", caloriesPer100g: 86 },
  { name: "Octopus", category: "seafood", caloriesPer100g: 82 },
  { name: "Oysters", category: "seafood", caloriesPer100g: 81 },
  { name: "Periwinkle", category: "seafood", caloriesPer100g: 0 },
  { name: "Prawns", category: "seafood", caloriesPer100g: 99 },
  { name: "Razor Clams", category: "seafood", caloriesPer100g: 0 },
  { name: "Rock Shrimp", category: "seafood", caloriesPer100g: 0 },
  { name: "Scallops", category: "seafood", caloriesPer100g: 111 },
  { name: "Shrimp", category: "seafood", caloriesPer100g: 99 },
  { name: "Snow Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Soft Shell Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Squid", category: "seafood", caloriesPer100g: 92 },
  { name: "Stone Crab", category: "seafood", caloriesPer100g: 0 },
  { name: "Uni", category: "seafood", caloriesPer100g: 0 },
  { name: "Whelk", category: "seafood", caloriesPer100g: 0 },
  { name: "Aleppo Pepper", category: "spice", caloriesPer100g: 0 },
  { name: "Allspice", category: "spice", caloriesPer100g: 263 },
  { name: "Amchur", category: "spice", caloriesPer100g: 0 },
  { name: "Anise", category: "spice", caloriesPer100g: 337 },
  { name: "Annatto Seeds", category: "spice", caloriesPer100g: 0 },
  { name: "Asafoetida", category: "spice", caloriesPer100g: 0 },
  { name: "Baharat", category: "spice", caloriesPer100g: 0 },
  { name: "Berbere", category: "spice", caloriesPer100g: 0 },
  { name: "Black Pepper", category: "spice", caloriesPer100g: 251 },
  { name: "Cajun Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Caraway", category: "spice", caloriesPer100g: 333 },
  { name: "Cardamom", category: "spice", caloriesPer100g: 311 },
  { name: "Cayenne Pepper", category: "spice", caloriesPer100g: 318 },
  { name: "Celery Seed", category: "spice", caloriesPer100g: 0 },
  { name: "Chili Powder", category: "spice", caloriesPer100g: 282 },
  { name: "Chipotle Powder", category: "spice", caloriesPer100g: 0 },
  { name: "Cinnamon", category: "spice", caloriesPer100g: 247 },
  { name: "Cloves", category: "spice", caloriesPer100g: 274 },
  { name: "Coriander", category: "spice", caloriesPer100g: 298 },
  { name: "Cumin", category: "spice", caloriesPer100g: 375 },
  { name: "Curry Powder", category: "spice", caloriesPer100g: 0 },
  { name: "Dukkah", category: "spice", caloriesPer100g: 0 },
  { name: "Fenugreek", category: "spice", caloriesPer100g: 323 },
  { name: "Five Spice Powder", category: "spice", caloriesPer100g: 0 },
  { name: "Furikake", category: "spice", caloriesPer100g: 0 },
  { name: "Garam Masala", category: "spice", caloriesPer100g: 0 },
  { name: "Grains of Paradise", category: "spice", caloriesPer100g: 0 },
  { name: "Green Peppercorns", category: "spice", caloriesPer100g: 0 },
  { name: "Horseradish", category: "spice", caloriesPer100g: 48 },
  { name: "Italian Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Jerk Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Kala Namak", category: "spice", caloriesPer100g: 0 },
  { name: "Long Pepper", category: "spice", caloriesPer100g: 0 },
  { name: "Mahlab", category: "spice", caloriesPer100g: 0 },
  { name: "Marash Pepper", category: "spice", caloriesPer100g: 0 },
  { name: "Mustard Powder", category: "spice", caloriesPer100g: 508 },
  { name: "Mustard Seed", category: "spice", caloriesPer100g: 508 },
  { name: "Nigella Seeds", category: "spice", caloriesPer100g: 0 },
  { name: "Nutmeg", category: "spice", caloriesPer100g: 525 },
  { name: "Old Bay Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Paprika", category: "spice", caloriesPer100g: 282 },
  { name: "Pink Peppercorns", category: "spice", caloriesPer100g: 0 },
  { name: "Poultry Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Ras el Hanout", category: "spice", caloriesPer100g: 0 },
  { name: "Saffron", category: "spice", caloriesPer100g: 310 },
  { name: "Shichimi Togarashi", category: "spice", caloriesPer100g: 0 },
  { name: "Sichuan Peppercorns", category: "spice", caloriesPer100g: 0 },
  { name: "Smoked Paprika", category: "spice", caloriesPer100g: 0 },
  { name: "Star Anise", category: "spice", caloriesPer100g: 337 },
  { name: "Sumac", category: "spice", caloriesPer100g: 349 },
  { name: "Taco Seasoning", category: "spice", caloriesPer100g: 0 },
  { name: "Turmeric", category: "spice", caloriesPer100g: 312 },
  { name: "Urfa Biber", category: "spice", caloriesPer100g: 0 },
  { name: "Vadouvan", category: "spice", caloriesPer100g: 0 },
  { name: "Wasabi", category: "spice", caloriesPer100g: 109 },
  { name: "White Pepper", category: "spice", caloriesPer100g: 296 },
  { name: "Za'atar", category: "spice", caloriesPer100g: 0 },
  { name: "Agave Nectar", category: "sweetener", caloriesPer100g: 310 },
  { name: "Barley Malt Syrup", category: "sweetener", caloriesPer100g: 0 },
  { name: "Brown Sugar", category: "sweetener", caloriesPer100g: 380 },
  { name: "Coconut Sugar", category: "sweetener", caloriesPer100g: 375 },
  { name: "Dark Brown Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Date Syrup", category: "sweetener", caloriesPer100g: 0 },
  { name: "Demerara Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Erythritol", category: "sweetener", caloriesPer100g: 0 },
  { name: "Golden Syrup", category: "sweetener", caloriesPer100g: 0 },
  { name: "Honey", category: "sweetener", caloriesPer100g: 304 },
  { name: "Light Brown Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Maple Syrup", category: "sweetener", caloriesPer100g: 260 },
  { name: "Molasses", category: "sweetener", caloriesPer100g: 290 },
  { name: "Monk Fruit Sweetener", category: "sweetener", caloriesPer100g: 0 },
  { name: "Muscovado Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Palm Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Pomegranate Molasses", category: "sweetener", caloriesPer100g: 0 },
  { name: "Rice Syrup", category: "sweetener", caloriesPer100g: 0 },
  { name: "Rock Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Sorghum Syrup", category: "sweetener", caloriesPer100g: 0 },
  { name: "Stevia", category: "sweetener", caloriesPer100g: 0 },
  { name: "Sugar", category: "sweetener", caloriesPer100g: 387 },
  { name: "Turbinado Sugar", category: "sweetener", caloriesPer100g: 0 },
  { name: "Xylitol", category: "sweetener", caloriesPer100g: 240 },
  { name: "Acorn Squash", category: "vegetable", caloriesPer100g: 40 },
  { name: "Alfalfa Sprouts", category: "vegetable", caloriesPer100g: 0 },
  { name: "Anaheim Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Ancho Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Arbol Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Artichoke", category: "vegetable", caloriesPer100g: 47 },
  { name: "Arugula", category: "vegetable", caloriesPer100g: 25 },
  { name: "Asparagus", category: "vegetable", caloriesPer100g: 20 },
  { name: "Bamboo Shoot", category: "vegetable", caloriesPer100g: 27 },
  { name: "Banana Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Belgian Endive", category: "vegetable", caloriesPer100g: 0 },
  { name: "Bell Pepper", category: "vegetable", caloriesPer100g: 20 },
  { name: "Bitter Melon", category: "vegetable", caloriesPer100g: 0 },
  { name: "Black Salsify", category: "vegetable", caloriesPer100g: 0 },
  { name: "Black Trumpet Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Black Truffle", category: "vegetable", caloriesPer100g: 0 },
  { name: "Bok Choy", category: "vegetable", caloriesPer100g: 13 },
  { name: "Broccoli", category: "vegetable", caloriesPer100g: 34 },
  { name: "Broccolini", category: "vegetable", caloriesPer100g: 0 },
  { name: "Brussels Sprouts", category: "vegetable", caloriesPer100g: 43 },
  { name: "Burdock Root", category: "vegetable", caloriesPer100g: 72 },
  { name: "Butternut Squash", category: "vegetable", caloriesPer100g: 45 },
  { name: "Cabbage", category: "vegetable", caloriesPer100g: 25 },
  { name: "Calabaza", category: "vegetable", caloriesPer100g: 0 },
  { name: "Carolina Reaper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Carrot", category: "vegetable", caloriesPer100g: 41 },
  { name: "Cauliflower", category: "vegetable", caloriesPer100g: 25 },
  { name: "Celeriac", category: "vegetable", caloriesPer100g: 0 },
  { name: "Celery", category: "vegetable", caloriesPer100g: 16 },
  { name: "Chanterelle", category: "vegetable", caloriesPer100g: 0 },
  { name: "Chard", category: "vegetable", caloriesPer100g: 19 },
  { name: "Chayote", category: "vegetable", caloriesPer100g: 0 },
  { name: "Chipotle Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Collard Greens", category: "vegetable", caloriesPer100g: 32 },
  { name: "Corn", category: "vegetable", caloriesPer100g: 86 },
  { name: "Cremini Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Crosne", category: "vegetable", caloriesPer100g: 0 },
  { name: "Cucumber", category: "vegetable", caloriesPer100g: 15 },
  { name: "Daikon", category: "vegetable", caloriesPer100g: 18 },
  { name: "Dandelion Greens", category: "vegetable", caloriesPer100g: 45 },
  { name: "Delicata Squash", category: "vegetable", caloriesPer100g: 0 },
  { name: "Eggplant", category: "vegetable", caloriesPer100g: 25 },
  { name: "Endive", category: "vegetable", caloriesPer100g: 17 },
  { name: "Enoki Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Fennel", category: "vegetable", caloriesPer100g: 31 },
  { name: "Fiddlehead Ferns", category: "vegetable", caloriesPer100g: 0 },
  { name: "Fresno Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Frisee", category: "vegetable", caloriesPer100g: 0 },
  { name: "Gai Lan", category: "vegetable", caloriesPer100g: 0 },
  { name: "Garlic", category: "vegetable", caloriesPer100g: 149 },
  { name: "Garlic Scapes", category: "vegetable", caloriesPer100g: 0 },
  { name: "Ghost Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Green Garlic", category: "vegetable", caloriesPer100g: 0 },
  { name: "Guajillo Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Habanero", category: "vegetable", caloriesPer100g: 0 },
  { name: "Hubbard Squash", category: "vegetable", caloriesPer100g: 0 },
  { name: "Jalapeno", category: "vegetable", caloriesPer100g: 0 },
  { name: "Jicama", category: "vegetable", caloriesPer100g: 38 },
  { name: "Kabocha Squash", category: "vegetable", caloriesPer100g: 0 },
  { name: "Kale", category: "vegetable", caloriesPer100g: 49 },
  { name: "King Trumpet Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Kohlrabi", category: "vegetable", caloriesPer100g: 27 },
  { name: "Komatsuna", category: "vegetable", caloriesPer100g: 0 },
  { name: "Leek", category: "vegetable", caloriesPer100g: 61 },
  { name: "Lettuce", category: "vegetable", caloriesPer100g: 15 },
  { name: "Lion's Mane Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Lobster Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Lotus Root", category: "vegetable", caloriesPer100g: 74 },
  { name: "Mache", category: "vegetable", caloriesPer100g: 0 },
  { name: "Maitake", category: "vegetable", caloriesPer100g: 0 },
  { name: "Malabar Spinach", category: "vegetable", caloriesPer100g: 0 },
  { name: "Manzano Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Matsutake", category: "vegetable", caloriesPer100g: 0 },
  { name: "Mizuna", category: "vegetable", caloriesPer100g: 0 },
  { name: "Morel", category: "vegetable", caloriesPer100g: 0 },
  { name: "Mung Bean Sprouts", category: "vegetable", caloriesPer100g: 0 },
  { name: "Mushroom", category: "vegetable", caloriesPer100g: 22 },
  { name: "Nameko Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "New Zealand Spinach", category: "vegetable", caloriesPer100g: 0 },
  { name: "Nopales", category: "vegetable", caloriesPer100g: 0 },
  { name: "Okra", category: "vegetable", caloriesPer100g: 33 },
  { name: "Onion", category: "vegetable", caloriesPer100g: 40 },
  { name: "Oyster Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Padron Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Parsnip", category: "vegetable", caloriesPer100g: 75 },
  { name: "Pasilla Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Patty Pan Squash", category: "vegetable", caloriesPer100g: 0 },
  { name: "Pea", category: "vegetable", caloriesPer100g: 81 },
  { name: "Pea Shoots", category: "vegetable", caloriesPer100g: 0 },
  { name: "Poblano", category: "vegetable", caloriesPer100g: 0 },
  { name: "Porcini", category: "vegetable", caloriesPer100g: 0 },
  { name: "Portobello Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Potato", category: "vegetable", caloriesPer100g: 77 },
  { name: "Purslane", category: "vegetable", caloriesPer100g: 0 },
  { name: "Radicchio", category: "vegetable", caloriesPer100g: 0 },
  { name: "Radish", category: "vegetable", caloriesPer100g: 16 },
  { name: "Ramps", category: "vegetable", caloriesPer100g: 0 },
  { name: "Rhubarb", category: "vegetable", caloriesPer100g: 21 },
  { name: "Romanesco", category: "vegetable", caloriesPer100g: 0 },
  { name: "Rutabaga", category: "vegetable", caloriesPer100g: 37 },
  { name: "Scotch Bonnet", category: "vegetable", caloriesPer100g: 0 },
  { name: "Scorzonera", category: "vegetable", caloriesPer100g: 0 },
  { name: "Sea Beans", category: "vegetable", caloriesPer100g: 0 },
  { name: "Serrano Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Shallot", category: "vegetable", caloriesPer100g: 72 },
  { name: "Shiitake", category: "vegetable", caloriesPer100g: 0 },
  { name: "Shimeji", category: "vegetable", caloriesPer100g: 0 },
  { name: "Shishito Pepper", category: "vegetable", caloriesPer100g: 0 },
  { name: "Spaghetti Squash", category: "vegetable", caloriesPer100g: 31 },
  { name: "Spinach", category: "vegetable", caloriesPer100g: 23 },
  { name: "Stinging Nettle", category: "vegetable", caloriesPer100g: 0 },
  { name: "Straw Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Sunchoke", category: "vegetable", caloriesPer100g: 0 },
  { name: "Sweet Potato", category: "vegetable", caloriesPer100g: 86 },
  { name: "Taro", category: "vegetable", caloriesPer100g: 112 },
  { name: "Tatsoi", category: "vegetable", caloriesPer100g: 0 },
  { name: "Thai Bird's Eye Chili", category: "vegetable", caloriesPer100g: 0 },
  { name: "Tomato", category: "vegetable", caloriesPer100g: 18 },
  { name: "Tomatillo", category: "vegetable", caloriesPer100g: 32 },
  { name: "Turnip", category: "vegetable", caloriesPer100g: 28 },
  { name: "Water Chestnut", category: "vegetable", caloriesPer100g: 0 },
  { name: "Watercress", category: "vegetable", caloriesPer100g: 11 },
  { name: "White Truffle", category: "vegetable", caloriesPer100g: 0 },
  { name: "Wood Ear Mushroom", category: "vegetable", caloriesPer100g: 0 },
  { name: "Yu Choy", category: "vegetable", caloriesPer100g: 0 },
  { name: "Zucchini", category: "vegetable", caloriesPer100g: 17 },
];

const seedIngredients = async () => {
  try {
    await connectDB();
    console.log("Database connected for seeding...");

    // Final duplicate check before insertion (by name)
    const uniqueIngredients = [];
    const seenNames = new Set();

    for (const ing of ingredients) {
      const lowerName = ing.name.toLowerCase().trim();
      if (!seenNames.has(lowerName)) {
        seenNames.add(lowerName);
        uniqueIngredients.push(ing);
      }
    }

    console.log(`Prepared ${uniqueIngredients.length} unique ingredients.`);

    await Ingredient.deleteMany({});
    console.log("Cleared existing ingredients.");

    await Ingredient.insertMany(uniqueIngredients);
    console.log(`Successfully seeded ${uniqueIngredients.length} ingredients!`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding ingredients:", error);
    process.exit(1);
  }
};

seedIngredients();
